version: '3.0'
services:
  base:
    build: ./packages/app
    env_file: .env
    volumes:
      - ./packages/app/src:/app/src
      - dist:/app/dist
  nginx:
    image: nginx
    env_file: .env
    ports:
      - "80:81"
    volumes:
      - dist:/app
volumes:
  dist: {}

