version: '3.0'
services:
  base:
    build: ./packages/app
    env_file: .env
    command: npm run gulp
    volumes:
      - ./packages/app/src:/app/src
      - dist:/app/dist
  nginx:
    image: nginx
    env_file: .env
    ports:
      - "80:80"
    volumes:
      - dist:/usr/share/nginx/html
volumes:
  dist: {}

