version: '1',
services:
  app:
    build: ./packages/app
    volumes:
      - ./packages/app/src:/src
      - dist:/dist
  nginx:
    image: nginx
    ports:
      -"8080:8080"
    volumes:
      - dist:/app
volumes:
  dist:
