version: '3.0'
services:
  app:
    build: ./packages/app
    env_file: ./.env
    volumes:
      - './packages/app/src:/app/src'
      - 'dist:/app/dist'
    command: tail -f /dev/null
  api:
    build: ./packages/api
    env_file: ./.env
    ports:
      - '3000:3000'
    volumes:
      - './packages/api/src:/api/src'
    command: tail -f /dev/null
  nginx:
    image: nginx
    ports:
      - '80:80'
    volumes:
      - 'dist:/usr/share/nginx/html'
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:5.6.0'
    environment:
      - 'ES_JAVA_OPTS=-Xms256m -Xmx256m -XX:ParallelGCThreads=1'
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - './packages/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml'
    ulimits:
      memlock:
        soft: -1
        hard: -1
      mem_limit: 5k
  eventstore:
    image: eventstore/eventstore
    environment:
      - EVENTSTORE_STATSPERIODSEC=600
    ports:
      - '2113:2113'
      - '1113:1113'
volumes:
  dist: {}
